import { Record } from '@servicenow/sdk/core'

Record({
    $id: Now.ID['6517600b47f0729092dc8c0fe16d4374'],
    table: 'item_option_new',
    data: {
        active: 'true',
        cat_item: 'f206e88747f0729092dc8c0fe16d4313',
        choice_direction: 'down',
        disable_initial_slot_fill: 'false',
        display_title: 'false',
        do_not_select_first: 'false',
        enable_also_request_for: 'false',
        global: 'false',
        help_tag: 'More information',
        hidden: 'false',
        include_none: 'true',
        layout: 'normal',
        lookup_unique: 'false',
        mandatory: 'true',
        map_to_field: 'false',
        mask_use_confirmation: 'false',
        mask_use_encryption: 'true',
        name: 'is_this_related_to_a_damage',
        not_available_conversation: 'false',
        order: '400',
        price_if_checked: '0',
        pricing_implications: 'false',
        question_text: 'Is this related to a damage?',
        read_only: 'false',
        rec_price_if_checked: '0',
        record_producer_table: 'x_snc_fleet_manage_fleet_management_task',
        save_script: `/** This script is executed before the Record is generated
* \`current\`- GlideRecord produced by Record Producer
* Don't use \`current.update()\` or \`current.insert()\` as the record is generated by Record Producer
* Don't use \`current.setValue('sys_class_name', 'xxx')\` as this will trigger reparent flow and can cause data loss
* Avoid \`current.setAbortAction()\` and generate a separate record
* Use \`producer.var1\` to access variables
*/`,
        scale_max: '5',
        scale_min: '0',
        show_help: 'false',
        show_help_on_load: 'false',
        type: '1',
        unique: 'false',
        use_dynamic_default: 'false',
        use_reference_qualifier: 'simple',
        visibility: '1',
        visible_bundle: 'true',
        visible_guide: 'true',
        visible_standalone: 'true',
        visible_summary: 'true',
    },
})
Record({
    $id: Now.ID['1437e40b47f0729092dc8c0fe16d43b2'],
    table: 'fx_price',
    data: {
        amount: '0',
        currency: 'USD',
        field: 'price_if_checked',
        id: '6517600b47f0729092dc8c0fe16d4374',
        reference_amount: '0',
        reference_currency: 'USD',
        table: 'item_option_new',
        type: 'calculated',
    },
})
Record({
    $id: Now.ID['d837e40b47f0729092dc8c0fe16d43b1'],
    table: 'fx_price',
    data: {
        amount: '0',
        currency: 'USD',
        field: 'rec_price_if_checked',
        id: '6517600b47f0729092dc8c0fe16d4374',
        reference_amount: '0',
        reference_currency: 'USD',
        table: 'item_option_new',
        type: 'calculated',
    },
})
