import { Record } from '@servicenow/sdk/core'

Record({
    $id: Now.ID['26c6acc747f0729092dc8c0fe16d431d'],
    table: 'item_option_new',
    data: {
        active: 'true',
        cat_item: 'f206e88747f0729092dc8c0fe16d4313',
        choice_direction: 'down',
        disable_initial_slot_fill: 'false',
        display_title: 'false',
        do_not_select_first: 'false',
        enable_also_request_for: 'false',
        global: 'false',
        help_tag: 'More information',
        hidden: 'false',
        include_none: 'false',
        layout: 'normal',
        lookup_unique: 'false',
        mandatory: 'true',
        map_to_field: 'false',
        mask_use_confirmation: 'false',
        mask_use_encryption: 'true',
        name: 'description',
        not_available_conversation: 'false',
        order: '200',
        price_if_checked: '0',
        pricing_implications: 'false',
        question_text: 'Request Details',
        read_only: 'false',
        rec_price_if_checked: '0',
        record_producer_table: 'x_snc_fleet_manage_fleet_management_task',
        save_script: `/** This script is executed before the Record is generated
* \`current\`- GlideRecord produced by Record Producer
* Don't use \`current.update()\` or \`current.insert()\` as the record is generated by Record Producer
* Don't use \`current.setValue('sys_class_name', 'xxx')\` as this will trigger reparent flow and can cause data loss
* Avoid \`current.setAbortAction()\` and generate a separate record
* Use \`producer.var1\` to access variables
*/`,
        scale_max: '5',
        scale_min: '0',
        show_help: 'false',
        show_help_on_load: 'false',
        type: '2',
        unique: 'false',
        use_dynamic_default: 'false',
        use_reference_qualifier: 'simple',
        visibility: '1',
        visible_bundle: 'true',
        visible_guide: 'true',
        visible_standalone: 'true',
        visible_summary: 'true',
    },
})
Record({
    $id: Now.ID['16d6ecc747f0729092dc8c0fe16d4394'],
    table: 'fx_price',
    data: {
        amount: '0',
        currency: 'USD',
        field: 'price_if_checked',
        id: '26c6acc747f0729092dc8c0fe16d431d',
        reference_amount: '0',
        reference_currency: 'USD',
        table: 'item_option_new',
        type: 'calculated',
    },
})
Record({
    $id: Now.ID['dad6ecc747f0729092dc8c0fe16d4393'],
    table: 'fx_price',
    data: {
        amount: '0',
        currency: 'USD',
        field: 'rec_price_if_checked',
        id: '26c6acc747f0729092dc8c0fe16d431d',
        reference_amount: '0',
        reference_currency: 'USD',
        table: 'item_option_new',
        type: 'calculated',
    },
})
