import { Record } from '@servicenow/sdk/core'

Record({
    $id: Now.ID['9386a4c747f0729092dc8c0fe16d4372'],
    table: 'fx_price',
    data: {
        amount: '0',
        currency: 'USD',
        field: 'price',
        id: 'f206e88747f0729092dc8c0fe16d4313',
        reference_amount: '0',
        reference_currency: 'USD',
        table: 'sc_cat_item_producer',
        type: 'calculated',
    },
})
Record({
    $id: Now.ID['f206e88747f0729092dc8c0fe16d4313'],
    table: 'sc_cat_item_producer',
    data: {
        access_type: 'restricted',
        active: 'true',
        additional_review: 'false',
        allow_edit: false,
        availability: 'on_desktop',
        billable: 'false',
        can_cancel: false,
        checked_out: 'false',
        cost: '0',
        create_universal_request: 'false',
        delivery_time: '1970-01-03 00:00:00',
        display_price_property: 'non_zero',
        fulfillment_automation_level: 'unspecified',
        hide_sp: 'false',
        ignore_price: 'true',
        make_item_non_conversational: 'false',
        mandatory_attachment: 'false',
        mobile_hide_price: 'false',
        mobile_picture_type: 'use_desktop_picture',
        name: 'Vehicle Maintenance Request',
        no_attachment_v2: 'true',
        no_cart: 'false',
        no_cart_v2: 'false',
        no_delivery_time_v2: 'false',
        no_order: 'false',
        no_order_now: 'false',
        no_proceed_checkout: 'false',
        no_quantity: 'false',
        no_quantity_v2: 'false',
        no_save_as_draft: 'false',
        no_search: 'false',
        no_wishlist_v2: 'false',
        omit_price: 'false',
        order: '0',
        owner: 'alexan.karasakalidis@snc',
        post_insert_script: `/**
* This script is executed after the record is generated. 
* \`current\` Is the GlideRecord produced by Record Producer. Use \`current.update()\` to update the record
* To access the variables, use \`producer.var1\` where var1 is the name of the variable
* To access the Record Producer use \`cat_item\`
*/`,
        preview:
            'JavaScript: popupOpenStandard("com.glideapp.servicecatalog_cat_item_view.do?v=1&sysparm_id=f206e88747f0729092dc8c0fe16d4313&sysparm_preview=true", "summary");',
        price: '0',
        redirect_url: 'generated_record',
        save_script: `/**
* This script is executed at every step save in Catalog Builder. 
* This script is executed before \`Script\` is executed.
* \`current\` Is the GlideRecord produced by Record Producer. 
* To access the variables, use \`producer.var1\` where var1 is the name of the variable
* To access the Record Producer use \`cat_item\`
*/`,
        script: `/** This script is executed before the Record is generated
* \`current\`- GlideRecord produced by Record Producer
* Don't use \`current.update()\` or \`current.insert()\` as the record is generated by Record Producer
* Don't use \`current.setValue('sys_class_name', 'xxx')\` as this will trigger reparent flow and can cause data loss
* Avoid \`current.setAbortAction()\` and generate a separate record
* Use \`producer.var1\` to access variables
*/

current.task_type = 2;`,
        show_variable_help_on_load: 'false',
        start_closed: 'false',
        state: 'published',
        table_name: 'x_snc_fleet_manage_fleet_management_task',
        type: 'item',
        use_sc_layout: 'true',
        version: '4',
        visible_bundle: 'true',
        visible_guide: 'true',
        visible_standalone: 'true',
    },
})
